# Generated by Django 5.2.8 on 2025-11-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="HallBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eventName", models.CharField(max_length=100)),
                ("contact", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("guests", models.IntegerField()),
                ("requirements", models.TextField(blank=True, null=True)),
                ("totalAmount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "appliedCoupon",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Indian", "Indian"),
                            ("Chinese", "Chinese"),
                            ("Rice & Biryani", "Rice & Biryani"),
                            ("Breads", "Breads"),
                            ("Desserts", "Desserts"),
                            ("Beverages", "Beverages"),
                        ],
                        max_length=50,
                    ),
                ),
                ("imageUrl", models.URLField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("guests", models.IntegerField()),
                ("notes", models.TextField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
